chore: impl .dockerignore to reduce container size
Painel-Solidario-RS/Painel-Solidario-RS pull request #40
Opened 2024-05-23 02:44 UTC by joaovperin

Criado .dockerignore para reduzir o tamanho dos containers gerados e otimizar o tempo de build. Também foi criado uma variável de ambiente opcional na API indicando se deve ou não utilizar SSL na conexão com o banco de dados, para que a aplicação consiga executar corretamente no banco do container (que não possui SSL).

2024-05-31 21:20 UTC, carla-reis-cr submitted a review, later dismissed

2024-06-02 15:31 UTC, gmullernh requested changes
Opa!
Creio que subir o ".env" no Dockerfile que será utilizado também ambiente produtivo seja uma má prática, uma vez que esse arquivo pode vazar ou sobreescrever as variáveis de ambiente do host. Por favor, remover a cópia do arquivo .env para dentro do container.

2024-06-02 18:17 UTC, joaovperin commented
@gmullernh sim sim, mas o deploy em produção é feito pelo github actions e o .env está no gitignore, então em produção ele não existe... Só em ambiente local. Tanto que foi necessário adicionar o wildcard pra que ele pudesse ser opcional

Pra remover ele teríamos que mapear todas as variáveis de ambiente e fazer o bind manual no compose, e aí ao rodar em dev, passar o argumento pra usar o env_file da pasta da API... É uma alternativa
O que tu acha?

2024-06-04 00:03 UTC, joaovperin commented
Feito o ajuste, já aproveitei e fiz alterações no router do traefik para remover o preffix /api/ ao redirecionar para a API.
Também ajustei o caminho pra execução no Dockerfile que estava errado, e adicionei as variáveis de ambiente que estavam faltando.

2024-06-05 23:10 UTC, gmullernh approved these changes
Ok!

2024-06-05 23:12 UTC, carla-reis-cr approved these changes

2024-06-05 23:13 UTC, merged